name: Build 🍄‍🟫

on:
    push:
        branches: [master]
        tags: ["v*"]
    pull_request:

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v7

            - name: Build
              run: ./build.ps1 -Version ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}

            - uses: actions/upload-artifact@v7
              with:
                  name: mushroomarizer
                  path: dist/mushroomarizer

            - name: Release
              if: github.ref_type == 'tag'
              run: gh release create ${{ github.ref_name }} dist/mushroomarizer.zip --generate-notes
              env:
                  GH_TOKEN: ${{ github.token }}
